version: "3.8"
services:
  db:
    image: postgres
    container_name: local_pgdb
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: opa_binance
    volumes:
      - local_pgdata:/var/lib/postgresql/data

volumes:
  local_pgdata:

