version: '3.8'

services:

  mongo:
    image: mongo:latest
    restart: unless-stopped
    container_name: mongo-container
    hostname: host-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    volumes:
      - ~/docker-volumes/mongodb:/data/db
      - ~/docker-volumes/mongodb/log:/var/log/mongodb/
    ports:
      - "27017:27017"