# options interval: https://python-binance.readthedocs.io/en/latest/constants.html
# options destination_source: csv, json, postgres, sqlite

binance_historical_data:
  destination_source: postgres
  table_name: historical_data
  symbol: BTCUSDT
  interval: 1d
  start: 1 Jan, 1990
  end: 1 day ago UTC

binance_streaming_data:
  destination_source: postgres
  table_name: streaming_data
  symbol: BTCUSDT
  interval: 5m
  start: 1 day ago UTC
  end: null

postgres:
  drivername: postgresql
  username: postgres
  password: 123456
  host: localhost
  port: 5437
  database: opa-binance

sqlite:
  drivername: sqlite
  database: data/opa-binance.db

mysql:
  drivername: pymysql
  username: root
  password: 123456
  host: 192.168.230.133
  port: 3306
  database: opa-binance

json:
  path: data/

csv:
  path: data/
