# options interval: https://python-binance.readthedocs.io/en/latest/constants.html
# options destination_source: csv, json, postgres, sqlite

binance_historical_data:
  destination_source: mysql
  table_name: historical_data
  symbol: BTCUSDT
  interval: 1d
  start: 1 Jan, 1990
  end: 1 day ago UTC

binance_streaming_data:
  destination_source: msyql
  table_name: streaming_data
  symbol: BTCUSDT
  interval: 5m
  start: 1 day ago UTC
  end: null
