postgres:
  drivername: postgresql
  username: postgres
  password: 123456
  host: 192.168.230.128
  port: 5432
  database: opa_binance

sqlite:
  drivername: sqlite
  database: /home/oscar/apps/sqlite/opa_binance.db

mysql:
  drivername: pymysql
  username: user
  password: 123456
  host: 192.168.230.133
  port: 3306
  database: opa_binance

mongodb:
  drivername: mongodb
  username: root
  password: 123456
  host: 192.168.230.128
  database: opa_binance
  port: 27017

json:
  path: /home/oscar/apps/json_files/

csv:
  path: /home/oscar/apps/csv_files/
