# options interval: https://python-binance.readthedocs.io/en/latest/constants.html
# options destination_source: csv, json, postgres, sqlite

binance_loader:
  destination_source: json
  table_name: bitcoin-last-day
  symbol: BTCUSDT
  interval: 5m
  start: 1 day ago UTC

postgres:
  drivername: postgresql
  username: postgres
  password: 123456
  host: localhost
  port: 5437
  database: opa-binance

sqlite:
  drivername: sqlite
  database: data/opa-binance.db

mysql:
  drivername: pymysql
  username: root
  password: 123456
  host: 192.168.230.133
  port: 3306
  database: opa-binance

json:
  path: data/

csv:
  path: data/
