version: "3.9"
services:

  fastpapi:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: fastapi
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - .:/collect_data/app
    command: poetry run uvicorn collect_data.app.main_postgres:api --reload --host 0.0.0.0
    #command: uvicorn /app/main_postgres:api --reload --host localhost --port 8002