version: "3.9"

services:
  configuration_service:
    container_name: opa-binance
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    image: opa-binance:latest
    ports:
      - 8000:8000