version: "3.9"

services:
  db:
    image: postgres
    container_name: local_pgdb
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: opa_binance
    volumes:
      - local_pgdata:/var/lib/postgresql/data

  mongodb:
    image: mongo:latest
    restart: unless-stopped
    container_name: mongo-container
    hostname: host-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    volumes:
      - ~/docker-volumes/mongodb:/data/db
      - ~/docker-volumes/mongodb/log:/var/log/mongodb/
    ports:
      - "27017:27017"

  fastapi:
    build: 
      context: .
      dockerfile: Dockerfile_Fastapi
    container_name: fastapi
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - .:/collect_data/api
    depends_on:
      - db
    command: poetry run uvicorn api.main:api --reload --host 0.0.0.0


  dash:
    build: 
      context: .
      dockerfile: Dockerfile_Dash
    container_name: dash
    restart: unless-stopped
    ports:
      - "8050:8050"  # Adjust the port numbers as needed
    volumes:
      - .:/collect_data/dash # Replace <your_dash_volume> and /path/in/container with appropriate volume information
    depends_on:
      - fastapi
    command: poetry run python3 dash/main.py

volumes:
  local_pgdata:   
