version: "3.9"

services:
  db:
    image: postgres
    container_name: local_pgdb
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: opa_binance
    volumes:
      - local_pgdata:/var/lib/postgresql/data

  fastpapi:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: fastapi
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - .:/collect_data/app
    depends_on:
      - db
    command: poetry run uvicorn collect_data.app.fastapi:api --reload --host 0.0.0.0

volumes:
  local_pgdata:   
